### ISSUE TITLE
help me?

### ISSUE THREAD

**Issue by schwagerik** [gabedunn-archive/devmod-v5#10]
https://imgur.com/a/6J45NLX

**Comment by redxtech** [comment]
There is no way that I can help you with just that.
Try running npm install first, configuring the bot, and then running it.

**Comment by redxtech** [comment]
I'm closing this as you've provided no new information for me to help you with. Feel free to re-open if there's any additional information that you want to provide.

**Comment by schwagerik** [comment]
not work..
