### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Pokevil-eng** [gabedunn-archive/devmod-v5#2]
can i contact you with discord? I just wants some help from you to host discord bot. Well i post here because i don't know any other way to chat with you. Sorry that i post in issue :( 

My tag: pokevil#9926

**Comment by redxtech** [comment]
I would prefer that you keep all support related contact to github issues, as that's what it's designed for.

**Comment by Pokevil-eng** [comment]
Sorry man but can you tell me which file makes devmod.db ?? I looked all files(i think) and i did not found anything that creates devmod.db

**Comment by redxtech** [comment]
It is no longer needed. It used to be created by sqlite.

**Comment by redxtech** [comment]
I'm going to close this.
