### ISSUE TITLE
[MISSING FILE] Im missing the entire config 

### ISSUE THREAD

**Issue by Motzumoto** [gabedunn-archive/devmod-v5#61]
In the readme, it says edit `devmod.config.js` but that is no where in the file, what should i do? make the file then add the "table of contents" type thing in the readme in it then go from there?

**Comment by Motzumoto** [comment]
a full walk through would be appreciated since i dont want to mess something up.

**Comment by S3B4S** [comment]
Most likely it's the `src/utils/default.config.js ` one ;)
Though it should indeed be updated in the README

**Comment by redxtech** [comment]
You have to make the config file yourself. Place it in the root directory and add all the fields you need.

**Comment by redxtech** [comment]
I'll close this since you haven't had any updates.
